Simplify error handling

diff --git a/spm b/spm
--- a/spm
+++ b/spm
@@ -22,22 +22,16 @@ umask u=rwx,go=
 ## Variables
 STORE_DIR="${PASSWORD_STORE_DIR:-${HOME}/.spm}"
 
-## Helper
-usage() {
-	cat 1>&2 <<-EOF
-	${1:+Error: ${1}}
-	USAGE: ${0##*/} add|list [-g]|search|show|help [[group/]entry|expression]
-	See spm(1) for more information.
-	EOF
-
-	exit ${1:+1}
+die() {
+    echo "${1}" >&2
+    exit 1
 }
 
 check() {
-	[ -n "${entry}" ] || usage 'no such entry'
+	[ -n "${entry}" ] || die 'no such entry'
 
 	[ $(printf '%s' "${entry}" | wc -l) -eq 0 ] ||
-		usage 'ambigious expression'
+		die 'ambigious expression'
 }
 
 age() {
@@ -48,7 +42,7 @@ readpw() {
 	[ -t 0 ] && stty -echo && printf '%s' "${1}"
 	IFS= read -r "${2}"
 	[ -t 0 ] && stty echo
-	[ -n "$(eval echo \"\$$2\")" ] || usage 'empty password'
+	[ -n "$(eval echo \"\$$2\")" ] || die 'empty password'
 }
 
 find() {
@@ -62,7 +56,7 @@ munge() {
 		eval ${2}=\"${abspath#${STORE_DIR}}\"
 		;;
 	*)
-		usage 'bad traversal'
+		die 'bad traversal'
 	esac
 }
 
@@ -72,7 +66,7 @@ view() {
 
 ## Commands
 add() {
-	[ -e "${STORE_DIR}"/"${1}" ] && usage 'entry already exists'
+	[ -e "${STORE_DIR}"/"${1}" ] && die 'entry already exists'
 
 	password=
 	readpw "Password for '${1}': " password
@@ -87,7 +81,7 @@ add() {
 }
 
 list() {
-	[ -d "${STORE_DIR}"/"${1:-}" ] || usage 'no such group'
+	[ -d "${STORE_DIR}"/"${1:-}" ] || die 'no such group'
 
 	tree ${gflag:+-d} -Fx -- "${STORE_DIR}"/"${1:-}" | view
 }
@@ -104,23 +98,23 @@ show() {
 ## Parse input
 [ ${#} -eq 0 ] || [ ${#} -gt 3 ] ||
 [ ${#} -eq 3 ] && [ "${1:-}" != list ] &&
-	usage 'wrong number of arguments'
+	die 'wrong number of arguments'
 
 case "${1}" in
 add|search|show)
-	[ -z "${2:-}" ] && usage 'empty name'
+	[ -z "${2:-}" ] && die 'empty name'
 	${1} "${2}"
 	;;
 list)
 	[ "${2:-}" = -g ] && gflag=1 && shift 1
-	[ ${#} -gt 2 ] && usage 'too many arguments'
+	[ ${#} -gt 2 ] && die 'too many arguments'
 	[ -n "${2:-}" ] && munge "${2}" relpath
 	list "${relpath:-}"
 	;;
 help)
-	usage
+	die
 	;;
 *)
-	usage 'invalid command'
+	die 'invalid command'
 	;;
 esac
